# Default values for dockerconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


imageCredentials:
  registry: docker.io/laflash
  username: ${{ secrets.DOCKER_USER }}
  password: ${{ secrets.DOCKER_PASS }}
  email: jody@laflash.guru
