apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-read-role
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - configmaps
    - pods
    - services
    verbs:
    - get
    - list
    - watch
    - create
    - update