apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:cluster-read-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "api-failover.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-read-role
  apiGroup: rbac.authorization.k8s.io