apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api-failover.fullname" . }}
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "api-failover.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "api-failover.serviceAccountName" . }}
    namespace: default

