apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-failover.fullname" . }}
  labels:
    {{- include "api-failover.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{.Values.service.externalPort}}
      targetPort: {{.Values.service.internalPort}}
      protocol: {{.Values.service.protocol}}
      name: http
  selector:
    {{- include "api-failover.selectorLabels" . | nindent 4 }}
