
harbor:
  expose:
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor.laflash-dev-tls
        notarySecretName: notary.laflash-dev-tls

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging" #"letsencrypt-staging" #"letsencrypt-prod"
        rancher.io/globalDNS: harbor.laflash-dev.com
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
        #    nginx.ingress.kubernetes.io/cors-max-age:
        # kubernetes.io/tls-acme: "true"
      hosts:
        core: harbor.laflash-dev.com
        notary: notary.laflash-dev.com

  externalURL: https://harbor.laflash-dev.com
  harborAdminPassword: admin

  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        # Use the existing PVC which must be created manually before bound,
        # and specify the "subPath" if the PVC is shared with other components
        existingClaim: ""
        # Specify the "storageClass" used to provision the volume. Or the default
        # StorageClass will be used(the default).
        # Set it to "-" to disable dynamic provisioning
        storageClass:
        subPath: ""
        accessMode: ReadWriteOnce
        size: 5Gi
      chartmuseum:
        existingClaim: ""
        storageClass:
        subPath: ""
        accessMode: ReadWriteOnce
        size: 5Gi
      jobservice:
        existingClaim: ""
        storageClass:
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
      # If external database is used, the following settings for database will
      # be ignored
      database:
        existingClaim: ""
        storageClass: 
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
      # If external Redis is used, the following settings for Redis will
      # be ignored
      redis:
        existingClaim: ""
        storageClass:
        subPath: ""
        accessMode: ReadWriteOnce
        size: 1Gi
      trivy:
        existingClaim: ""
        storageClass:
        subPath: ""
        accessMode: ReadWriteOnce
        size: 5Gi
